spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET}
jwt.expiration.access=${JWT_EXPIRATION_ACCESS}
jwt.expiration.refresh=${JWT_EXPIRATION_REFRESH}

storage.resumes-dir=${STORAGE_RESUMES_DIR}

openai.api-key=${OPENAI_API_KEY}
openai.model=${OPENAI_MODEL}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

jsearch.api-key=${JSEARCH_API_KEY}
jsearch.api-host=${JSEARCH_API_HOST}
jsearch.base-url=${JSEARCH_BASE_URL}

github.token=${GITHUB_TOKEN:}

encryption.secret=${ENCRYPTION_SECRET}
encryption.salt=${ENCRYPTION_SALT}

spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.frontend-url=${FRONTEND_URL}