spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET}
jwt.expiration.access=${JWT_EXPIRATION_ACCESS}
jwt.expiration.refresh=${JWT_EXPIRATION_REFRESH}

storage.resumes-dir=${STORAGE_RESUMES_DIR}

openai.api-key=${OPENAI_API_KEY}
openai.model=${OPENAI_MODEL}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

jsearch.api-key=${JSEARCH_API_KEY}
jsearch.api-host=${JSEARCH_API_HOST}
jsearch.base-url=${JSEARCH_BASE_URL}

github.token=${GITHUB_TOKEN:}