spring.datasource.url=jdbc:postgresql://localhost:5432/searchjobs
spring.datasource.username=postgres
spring.datasource.password=2210

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=3f8a2d1c9e4b7f0a6d3c2e1b8f5a9d4c7e0b3f6a9d2c5e8b1f4a7d0c3e6b9f2
jwt.expiration.access=900000
jwt.expiration.refresh=604800000